version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
      - image: redis:6.2.6
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt install -y redis-tools
      - run: redis-cli ping
      - run: redis-cli LPUSH mylist a b c d
      - run: redis-cli --csv LRANGE mylist 0 -1
